package com.example.summerpracticeseries

object SeriesRepository {
    val series = arrayListOf(
        Series(0,
            "Euphoria",
            "Drama",
            "https://i.pinimg.com/564x/6d/dd/cf/6dddcff84b46a256d7dca76dab4acf5e.jpg",
            "After rehab, rebel Ru gets used to school life again. The most outspoken teen drama of the decade",
        "2019 — ..."),
        Series(1,
            "Noragami",
            "Anime",
            "https://i.pinimg.com/564x/09/1e/6d/091e6d9de9b0738d0ceb6045a4be8d99.jpg",
            "Adventures of an unlucky deity in an unpredictable world of people",
        "2014 — 2015"),
        Series(2,
            "Attack on Titan",
            "Anime",
            "https://i.pinimg.com/564x/3a/b6/9f/3ab69f070b29055e3a543ba5914bd3c4.jpg",
            "A teenager takes revenge on humanoid cannibals for the murder of his mother. Cult anime series based on post-apocalyptic manga",
        "2013 — ..."),
        Series(3,
            "Rick and Morty",
            "Sitcom",
            "https://i.pinimg.com/564x/dc/09/28/dc09288c93009a7c4c7031b246308807.jpg",
            "Funny and inventive adventures of a mad genius and his grandson",
        "2013 — ..."),
        Series(4,
            "Jujutsu Kaisen",
            "Anime",
            "https://i.pinimg.com/564x/f4/fc/45/f4fc45dec3f59809e5e4d9becf026c0b.jpg",
            "A world in which demons feed on people, and they don't even know about it. And only high school student Yuji Itadori can resist them",
        "2020 — 2021"),
        Series(5,
            "Wayne",
            "Action",
            "https://i.pinimg.com/564x/15/e6/bd/15e6bdcd2e5a6deed28e7edd17d3b001.jpg",
            "A troubled teenager runs away from home to return his father's stolen car. An ode to the rebels from the authors of «Deadpool»",
            "2019"),
        Series(6,
            "Parasite: The Doctrine of Life",
            "Anime",
            "https://i.pinimg.com/564x/39/51/59/3951595c0f7dc7f7fd5359317cfb7af8.jpg",
            "An extraterrestrial symbiote settles in the right hand of a high school student",
            "2014 — 2015"),
        Series(7,
            "Sex Education",
            "Comedy drama",
            "https://i.pinimg.com/564x/09/6b/62/096b625318bd3646f6869561a42ac401.jpg",
            "Shy and unsociable teenage virgin Otis lives with his mother, who works as a sex therapist. Teaming up with classmate Maeve, Otis conducts therapy sessions for his peers to help them deal with awkward and confusing situations",
            "2019 — ..."),
        Series(8,
            "The End of the F***ing World",
            "Drama",
            "https://i.pinimg.com/564x/b1/87/08/b187083a48c93771c4e3ef0504d83329.jpg",
            "James is seventeen and he is sure that he is a psychopath. Alice is also seventeen, she is a capricious new girl at school. They have a half-turn teenage romance, and Alice persuades James to start looking for her father. James needs something from Alice too",
            "2017 — 2019"),
        Series(9,
            "Stranger Things",
            "Science fiction",
            "https://i.pinimg.com/564x/01/a9/dd/01a9dd5fb310e6471b17bc503dda0680.jpg",
            "1980s, a quiet provincial American town. The favorable course of local life is disrupted by the mysterious disappearance of a teenager named Will. His best friend Mike starts his own investigation. He is sure that he is close to the solution, and now he has to find himself in the epicenter of a fierce battle of otherworldly forces",
            "2016 — ..."),
    )
}